<?php

namespace ContainerY2qm9Hx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LU6Y8GvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LU6Y8Gv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LU6Y8Gv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AthleteController::showAllAthletes' => ['privates', '.service_locator.BI4oBB4', 'get_ServiceLocator_BI4oBB4Service', true],
            'App\\Controller\\CalendrierController::showAllCalendriers' => ['privates', '.service_locator.ZeuNW5_', 'get_ServiceLocator_ZeuNW5Service', true],
            'App\\Controller\\CategorieController::showAllCategories' => ['privates', '.service_locator.MmjVgc3', 'get_ServiceLocator_MmjVgc3Service', true],
            'App\\Controller\\CompetitionController::showAllCompetition' => ['privates', '.service_locator.TPsfBmY', 'get_ServiceLocator_TPsfBmYService', true],
            'App\\Controller\\EpreuveController::showAllEpreuves' => ['privates', '.service_locator.Jwan1D1', 'get_ServiceLocator_Jwan1D1Service', true],
            'App\\Controller\\ResultatController::showAllResultat' => ['privates', '.service_locator.QnoB3jK', 'get_ServiceLocator_QnoB3jKService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AthleteController:showAllAthletes' => ['privates', '.service_locator.BI4oBB4', 'get_ServiceLocator_BI4oBB4Service', true],
            'App\\Controller\\CalendrierController:showAllCalendriers' => ['privates', '.service_locator.ZeuNW5_', 'get_ServiceLocator_ZeuNW5Service', true],
            'App\\Controller\\CategorieController:showAllCategories' => ['privates', '.service_locator.MmjVgc3', 'get_ServiceLocator_MmjVgc3Service', true],
            'App\\Controller\\CompetitionController:showAllCompetition' => ['privates', '.service_locator.TPsfBmY', 'get_ServiceLocator_TPsfBmYService', true],
            'App\\Controller\\EpreuveController:showAllEpreuves' => ['privates', '.service_locator.Jwan1D1', 'get_ServiceLocator_Jwan1D1Service', true],
            'App\\Controller\\ResultatController:showAllResultat' => ['privates', '.service_locator.QnoB3jK', 'get_ServiceLocator_QnoB3jKService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AthleteController::showAllAthletes' => '?',
            'App\\Controller\\CalendrierController::showAllCalendriers' => '?',
            'App\\Controller\\CategorieController::showAllCategories' => '?',
            'App\\Controller\\CompetitionController::showAllCompetition' => '?',
            'App\\Controller\\EpreuveController::showAllEpreuves' => '?',
            'App\\Controller\\ResultatController::showAllResultat' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AthleteController:showAllAthletes' => '?',
            'App\\Controller\\CalendrierController:showAllCalendriers' => '?',
            'App\\Controller\\CategorieController:showAllCategories' => '?',
            'App\\Controller\\CompetitionController:showAllCompetition' => '?',
            'App\\Controller\\EpreuveController:showAllEpreuves' => '?',
            'App\\Controller\\ResultatController:showAllResultat' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
