<?php

namespace ContainerY2qm9Hx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCalendrierTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\CalendrierType' shared autowired service.
     *
     * @return \App\Form\CalendrierType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/CalendrierType.php';

        return $container->privates['App\\Form\\CalendrierType'] = new \App\Form\CalendrierType();
    }
}
