<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY2qm9Hx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY2qm9Hx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY2qm9Hx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY2qm9Hx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerY2qm9Hx\App_KernelDevDebugContainer([
    'container.build_hash' => 'Y2qm9Hx',
    'container.build_id' => '9a830e7a',
    'container.build_time' => 1616665114,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY2qm9Hx');
